import { StyleSheet } from "react-native";
const sigupStyle = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#FFFFFF",
	},
	scrollView: {
		flex: 1,
		backgroundColor: "#FFFFFF",
		paddingTop: 77,
	},

	header: {
		color: "#191D31",
		fontSize: 22,
		fontWeight: "bold",
		marginBottom: 11,
		marginLeft: 25,
	},
	wellcome: {
		color: "#A7AEC1",
		fontSize: 14,
		marginBottom: 38,
		marginHorizontal: 25,
	},
	userName: {
		color: "#191D31",
		fontSize: 16,
		fontWeight: "bold",
		marginBottom: 10,
		marginLeft: 26,
	},
	input: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#FBFBFD",
		borderColor: "#F9F9F9",
		borderRadius: 15,
		borderWidth: 1,
		paddingHorizontal: 14,
		marginBottom: 25,
		marginHorizontal: 24,
	},
	userNameigm: {
		width: 24,
		height: 24,
		marginRight: 16,
	},
	textInputUserName: {
		color: "#A7AEC1",
		fontSize: 14,
		flex: 1,
		paddingVertical: 15,
	},
	contactPhoneNumber: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#FBFBFD",
		borderColor: "#F9F9F9",
		borderRadius: 15,
		borderWidth: 1,
		paddingHorizontal: 14,
		marginBottom: 25,
		marginHorizontal: 24,
	},
	phoneNumber: {
		color: "#191D31",
		fontSize: 16,
		fontWeight: "bold",
		marginBottom: 10,
		marginLeft: 26,
	},
	phoneNumberimg: {
		width: 24,
		height: 24,
		marginRight: 16,
	},
	textInputPhoneNumber: {
		color: "#A7AEC1",
		fontSize: 14,
		flex: 1,
		paddingVertical: 15,
	},

	textInputPasssWord: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#FBFBFD",
		borderColor: "#F9F9F9",
		borderRadius: 15,
		borderWidth: 1,
		paddingVertical: 15,
		paddingHorizontal: 14,
		marginBottom: 50,
		marginHorizontal: 24,
		justifyContent: "space-between",
	},
	titlePassword: {
		color: "#191D31",
		fontSize: 16,
		fontWeight: "bold",
		marginBottom: 10,
		marginLeft: 26,
	},
	ViewPassword: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#FBFBFD",
		borderColor: "#F9F9F9",
		borderRadius: 15,
		borderWidth: 1,
		paddingVertical: 15,
		paddingHorizontal: 14,
		marginBottom: 50,
		marginHorizontal: 24,
	},
	password: {
		color: "#A7AEC1",
		fontSize: 14,
		flex: 1,
		paddingVertical: 15,
	},
	passwordIGM: {
		width: 24,
		height: 24,
		marginRight: 16,
	},
	passwordIGM1: {
		width: 24,
		height: 24,
		marginRight: 16,
	},
	eye: {
		flex: 1,
	},
	eyeIMG: {
		width: 24,
		height: 23,
	},
	ClickSignup: {
		alignItems: "center",
		backgroundColor: "#77634C",
		borderRadius: 30,
		paddingVertical: 23,
		marginBottom: 25,
		marginHorizontal: 24,
	},
	textSignup: {
		color: "#FFFFFF",
		fontSize: 16,
		fontWeight: "bold",
	},
	loginQickLy: {
		color: "#A7AEC1",
		fontSize: 14,
		marginBottom: 19,
		marginHorizontal: 150,
	},
	signinGG: {
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "#FFFFFF",
		borderColor: "#F3F3F3",
		borderRadius: 30,
		borderWidth: 2,
		paddingVertical: 15,
		marginBottom: 15,
		marginHorizontal: 24,
	},
	siginIMG: {
		width: 31,
		height: 26,
		marginRight: 11,
	},
	textSigin: {
		color: "#191D31",
		fontSize: 16,
		fontWeight: "bold",
	},
	siginTikTok: {
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "#FFFFFF",
		borderColor: "#F3F3F3",
		borderRadius: 30,
		borderWidth: 2,
		paddingVertical: 15,
		marginBottom: 62,
		marginHorizontal: 24,
	},
	sigintiktokIMG: {
		width: 29,
		height: 27,
		marginRight: 11,
	},
	texttiktokSigin: { color: "#191D31", fontSize: 16, fontWeight: "bold" },
});
export default sigupStyle;
