server:
  port: 8080
  servlet:
    context-path: /zen8labs-system

jwt:
  signerKey: "1lD9fsDTGBoeO+PtSfpBlE87zHJSoGWb1g3ptVl7qlfPEXCdXAw1NjhDlELjTIEX"
  valid-duration: 3600  # in second
  refreshable-duration: 360000  # in seconds

open:
  api:
    title: API document
    version: 1.0.0
    description: Banking System
    serverUrl: http://localhost:8080/zen8labs-system
    serverName: Server Test
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dodinhtuanyb2k4@gmail.com
    password: fvocofqpeseipsia
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        mail:
          debug: true
